import { ArrowLeft, ArrowRight, CalendarDays, CheckCircle2, Clock3, HeartHandshake, Mail, MapPin, MessageCircle, Search, Send, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useRoute } from "wouter";
import { toast } from "sonner";
import { PageLayout } from "@/components/SiteShell";
import { ASSETS, DEMO_EVENTS, DEMO_GALLERY, DEMO_NEWS, formatDate } from "@/lib/content";
import { trpc } from "@/lib/trpc";

function PageHero({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="page-hero"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></section>; }

export function NewsPage() {
  const [search, setSearch] = useState(""); const [category, setCategory] = useState("all");
  const { data: apiNews } = trpc.portal.news.useQuery({ search: search || undefined, category }); const { data: apiCategories } = trpc.portal.categories.useQuery();
  const source = apiNews?.length ? apiNews : DEMO_NEWS;
  const stories = useMemo(() => source.filter(item => (!search || item.title.toLowerCase().includes(search.toLowerCase()) || item.excerpt.toLowerCase().includes(search.toLowerCase())) && (category === "all" || item.categorySlug === category)), [source, search, category]);
  const categories = apiCategories?.length ? apiCategories : [{ id: 1, name: "Comunidade", slug: "comunidade" }, { id: 2, name: "Cultura", slug: "cultura" }, { id: 3, name: "Meio ambiente", slug: "meio-ambiente" }];
  return <PageLayout><PageHero eyebrow="INFORMAÇÃO QUE APROXIMA" title="Notícias" text="Acompanhe as iniciativas, avisos e histórias que movimentam Juruti Velho." /><section className="section"><div className="container"><div className="news-filter"><label><Search size={18} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar uma notícia" aria-label="Buscar notícias" /></label><div className="filter-chips"><button className={category === "all" ? "selected" : ""} onClick={() => setCategory("all")}>Todas</button>{categories.map(item => <button key={item.id} className={category === item.slug ? "selected" : ""} onClick={() => setCategory(item.slug)}>{item.name}</button>)}</div></div>{stories.length ? <div className="news-list-grid">{stories.map(story => <article className="news-card" key={story.id}><div className="news-image"><img src={story.coverImage || ASSETS.community} alt="" /><span>{story.category || "ACORJUVE"}</span></div><div className="news-content"><p className="meta">{formatDate(story.publishedAt)} · {story.authorName}</p><h2>{story.title}</h2><p>{story.excerpt}</p><Link href={`/noticias/${story.slug}`} className="card-link">Ler notícia <ArrowRight size={17} /></Link></div></article>)}</div> : <div className="empty-state"><Search size={28} /><h2>Nenhuma notícia encontrada</h2><p>Tente outra busca ou escolha uma categoria diferente.</p></div>}</div></section></PageLayout>;
}

export function ArticlePage() {
  const [, params] = useRoute("/noticias/:slug"); const slug = params?.slug || "";
  const { data: article } = trpc.portal.newsBySlug.useQuery({ slug }, { enabled: !!slug });
  const fallback = DEMO_NEWS.find(item => item.slug === slug); const story = article || fallback;
  const { data: approvedComments } = trpc.portal.comments.useQuery({ newsId: story?.id || 0 }, { enabled: !!story && story.id > 0 }); const addComment = trpc.portal.addComment.useMutation({ onSuccess: data => toast.success(data.message), onError: err => toast.error(err.message) });
  const [name, setName] = useState(""); const [comment, setComment] = useState("");
  if (!story) return <PageLayout><div className="container section empty-state"><h1>Notícia não encontrada</h1><Link className="text-link" href="/noticias"><ArrowLeft size={16} /> Voltar para notícias</Link></div></PageLayout>;
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (story.id < 0) { toast.info("Comentários estão prontos para uso quando esta notícia for publicada no painel."); return; } addComment.mutate({ newsId: story.id, authorName: name, content: comment }); setComment(""); };
  return <PageLayout><article className="article"><div className="container article-head"><Link href="/noticias" className="back-link"><ArrowLeft size={16} /> Notícias</Link><span className="eyebrow">{story.category || "ACORJUVE"}</span><h1>{story.title}</h1><p className="lead">{story.excerpt}</p><p className="meta">Por {story.authorName} · {formatDate(story.publishedAt)}</p></div><img className="article-cover" src={story.coverImage || ASSETS.community} alt="" /><div className="container article-body">{story.content.split("\n\n").map((paragraph, i) => <p key={i}>{paragraph}</p>)}<hr /><section className="comments"><div><span className="eyebrow"><MessageCircle size={15} /> Participação</span><h2>Deixe sua opinião</h2><p>Seu comentário será revisado antes de aparecer publicamente.</p></div><form onSubmit={submit} className="comment-form"><label>Seu nome<input required minLength={2} value={name} onChange={e => setName(e.target.value)} placeholder="Como podemos chamar você?" /></label><label>Seu comentário<textarea required minLength={4} value={comment} onChange={e => setComment(e.target.value)} placeholder="Escreva com respeito e colaboração." rows={4} /></label><button disabled={addComment.isPending} className="button button-primary">{addComment.isPending ? "Enviando..." : "Enviar comentário"} <Send size={16} /></button></form>{approvedComments?.length ? <div className="published-comments">{approvedComments.map(item => <div key={item.id}><strong>{item.authorName}</strong><span>{formatDate(item.createdAt)}</span><p>{item.content}</p></div>)}</div> : null}</section></div></article></PageLayout>;
}

export function EventsPage() { const { data } = trpc.portal.events.useQuery(); const items = data?.length ? data : DEMO_EVENTS; return <PageLayout><PageHero eyebrow="AGENDA ABERTA" title="Eventos" text="Encontros para conversar, aprender, celebrar e cuidar de Juruti Velho." /><section className="section"><div className="container event-cards">{items.map(event => <article key={event.id} className="event-card"><img src={event.imageUrl || ASSETS.river} alt="" /><div><div className="date-block small"><strong>{new Date(event.startAt).getDate().toString().padStart(2, "0")}</strong><span>{new Intl.DateTimeFormat("pt-BR", { month: "short" }).format(new Date(event.startAt)).replace(".", "")}</span></div><h2>{event.title}</h2><p>{event.description}</p><div className="event-facts"><span><Clock3 size={16} /> {formatDate(event.startAt, true)}</span><span><MapPin size={16} /> {event.location}</span></div></div></article>)}</div></section></PageLayout>; }

export function GalleryPage() { const [filter, setFilter] = useState("all"); const [selected, setSelected] = useState<number | null>(null); const { data } = trpc.portal.gallery.useQuery({ category: filter }); const images = data?.length ? data : DEMO_GALLERY; const categories = ["all", ...Array.from(new Set(images.map(image => image.category)))]; const visible = filter === "all" ? images : images.filter(image => image.category === filter); const opened = images.find(item => item.id === selected); return <PageLayout><PageHero eyebrow="MEMÓRIAS EM IMAGEM" title="Galeria" text="Momentos, paisagens e encontros que formam a memória viva da nossa comunidade." /><section className="section"><div className="container"><div className="filter-chips gallery-chips">{categories.map(item => <button key={item} className={filter === item ? "selected" : ""} onClick={() => setFilter(item)}>{item === "all" ? "Todos" : item}</button>)}</div><div className="gallery-page-grid">{visible.map(image => <button key={image.id} className="gallery-photo" onClick={() => setSelected(image.id)}><img src={image.imageUrl} alt={image.altText} /><span><strong>{image.title}</strong><small>{image.category}</small></span></button>)}</div></div></section>{opened && <div className="lightbox" role="dialog" aria-modal="true" aria-label={opened.title} onClick={() => setSelected(null)}><button aria-label="Fechar visualização" onClick={() => setSelected(null)}>×</button><img src={opened.imageUrl} alt={opened.altText} /></div>}</PageLayout>; }

export function AboutPage() { return <PageLayout><PageHero eyebrow="RAÍZES E PROPÓSITOS" title="Sobre a ACORJUVE" text="Uma associação comunitária que acredita na força de construir junto." /><section className="section"><div className="container about-grid"><div><span className="eyebrow"><HeartHandshake size={15} /> Nossa história</span><h2>Nasce da escuta. Cresce com a participação.</h2><p>A ACORJUVE — Associação Comunitária de Juruti Velho — é um espaço de organização, diálogo e cooperação. Trabalhamos para aproximar pessoas, fortalecer os vínculos comunitários e apoiar iniciativas que cuidam do nosso território.</p><p>Este portal é uma extensão desse compromisso: um lugar aberto para acompanhar ações, compartilhar informações e descobrir maneiras de participar.</p></div><img src={ASSETS.culture} alt="Comunidade reunida em uma oficina de saberes locais" /></div></section><section className="values-section"><div className="container"><div className="section-heading"><div><span className="eyebrow light">NOSSO COMPROMISSO</span><h2>O que move a ACORJUVE</h2></div></div><div className="values-grid"><div><Users /><h3>Participação</h3><p>Decisões e ações construídas com as pessoas que vivem a comunidade.</p></div><div><HeartHandshake /><h3>Cuidado</h3><p>Atenção aos vínculos, aos espaços comuns e às necessidades do território.</p></div><div><CheckCircle2 /><h3>Transparência</h3><p>Informação acessível e diálogo aberto em cada iniciativa.</p></div></div></div></section><section className="section"><div className="container objectives"><div><span className="eyebrow">FRENTES DE ATUAÇÃO</span><h2>Projetos que aproximam.</h2></div><ul><li>Valorização da cultura e dos saberes locais</li><li>Ações de educação ambiental e cuidado com o território</li><li>Mobilização comunitária e participação popular</li><li>Apoio a encontros, oficinas e atividades de convivência</li></ul></div></section></PageLayout>; }

export function ContactPage() { const contact = trpc.portal.contact.useMutation({ onSuccess: () => { toast.success("Mensagem enviada. A ACORJUVE entrará em contato em breve."); setForm({ name: "", email: "", subject: "", message: "" }); }, onError: err => toast.error(err.message) }); const [form, setForm] = useState({ name: "", email: "", subject: "", message: "" }); const update = (field: keyof typeof form) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm({ ...form, [field]: e.target.value }); return <PageLayout><PageHero eyebrow="ESTAMOS POR PERTO" title="Fale com a gente" text="Envie uma mensagem, compartilhe uma ideia ou saiba como participar das ações da associação." /><section className="section"><div className="container contact-grid"><div className="contact-info"><span className="eyebrow"><HeartHandshake size={15} /> Contato</span><h2>Uma conversa pode abrir novos caminhos.</h2><p>Preencha o formulário ao lado. Sua mensagem chega diretamente à equipe da ACORJUVE.</p><div><MapPin /><span><strong>Comunidade</strong>Juruti Velho · Juruti, Pará</span></div><div><Mail /><span><strong>E-mail</strong>contato@acorjuve.org.br</span></div><div><CalendarDays /><span><strong>Atendimento</strong>De segunda a sexta, em horário comunitário</span></div></div><form className="contact-form" onSubmit={e => { e.preventDefault(); contact.mutate(form); }}><label>Seu nome<input required value={form.name} onChange={update("name")} placeholder="Digite seu nome" /></label><label>Seu e-mail<input required type="email" value={form.email} onChange={update("email")} placeholder="voce@email.com" /></label><label>Assunto<input required value={form.subject} onChange={update("subject")} placeholder="Como podemos ajudar?" /></label><label>Mensagem<textarea required rows={5} value={form.message} onChange={update("message")} placeholder="Escreva sua mensagem" /></label><button disabled={contact.isPending} className="button button-primary">{contact.isPending ? "Enviando..." : "Enviar mensagem"} <Send size={16} /></button></form></div></section></PageLayout>; }
